version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - hello_world
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  hello_world:
    image: hello-world:latest
    environment:
      - NODE_ENV=local
      - PORT=3000
      - TZ=Asia/Kolkata
      - ENABLE_CONSOLE_LOGS=false
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/opt/org/hello-world/dist/logs
      - ./data:/opt/org/hello-world/dist/data
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge